ahc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('accounts.urls')),
    path('', include('main.urls')),
    path('hr/', include('hr.urls')),
]

hr/urls.py
from django.urls import path
from . import views
from .views import Hr_main_view

from . import views
app_name = "hr"
urlpatterns = [
    # path('', views.empl, name='hr'),
    path('', Hr_main_view.as_view(), name='hr'),
    path('new', views.newemployee, name="newemployee"),


    path('emp', views.emp, name='emp'),
    path('save_emp', views.save_emp, name='save_emp'),

    path('import_actions', views.import_actions, name='import_actions'),
    path('import_area_side', views.import_area_side, name='import_area_side'),
    path('import_area_side', views.import_area_side, name='import_area_side'),
    path('import_eclass', views.import_eclass, name='import_eclass'),
    path('import_general_specialization', views.import_general_specialization, name='import_general_specialization'),
    path('import_jobs', views.import_jobs, name='import_jobs'),
    path('import_nationalities', views.import_nationalities, name='import_nationalities'),
    path('import_specialization', views.import_specialization, name='import_specialization'),

    path('import_employees', views.import_employees, name='import_employees'),
]

main/urls.py
from django.urls import path

from hr.urls import app_name
from . import views

app_name = "main"

urlpatterns = [
    path('', views.main, name='main'),
    # path('hr/', views.hr, name='hr'),
    path('payroll/', views.payroll, name='payroll'),
    path('assignment/', views.assignment, name='assignment'),
    path('jobs/', views.jobs, name='jobs'),
    path('recruitment/', views.recruitment, name='recruitment'),
    path('usersmanagement/', views.usersmanagement, name='usersmanagement'),
    path('assignment/newassignment/', views.newassignment, name='newassignment'),
]

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Document</title>
</head>
<body class="noto-kufi-arabic-fo">
    <nav class="navbar">
        <a href="{% url 'main:main' %}"  class="title" style="text-decoration: none"><h1>لوحة التحكم</h1></a>
        <ul>
            <a href="{% url 'hr:hr' %}"><li>الموارد البشرية</li></a>
            <a href="{% url 'main:payroll' %}"><li>الرواتب</li></a>
            <a href="{% url 'main:assignment' %}"><li>التكليف</li></a>
            <a href="{% url 'main:jobs' %}"><li>الوظائف</li></a>
            <a href="{% url 'main:recruitment' %}"><li>التوظيف</li></a>
            <a href="{% url 'main:usersmanagement' %}"><li>ادارة المستخدمين</li></a>
        </ul>
        <h4>تسجيل دخول</h4>
    </nav>
    {% block container %}
    {% endblock %}

    <script src="{% static 'js/main.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>

</body>
</html>