ahc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('accounts.urls')),
    path('', include('main.urls')),
    path('hr/', include('hr.urls')),
]

hr/urls.py
from django.urls import path
from . import views
from .views import Hr_main_view

from . import views
app_name = "hr"
urlpatterns = [
    # path('', views.empl, name='hr'),
    path('', Hr_main_view.as_view(), name='hr'),
    path('new', views.newemployee, name="newemployee"),


    path('emp', views.emp, name='emp'),
    path('save_emp', views.save_emp, name='save_emp'),

    path('import_actions', views.import_actions, name='import_actions'),
    path('import_area_side', views.import_area_side, name='import_area_side'),
    path('import_area_side', views.import_area_side, name='import_area_side'),
    path('import_eclass', views.import_eclass, name='import_eclass'),
    path('import_general_specialization', views.import_general_specialization, name='import_general_specialization'),
    path('import_jobs', views.import_jobs, name='import_jobs'),
    path('import_nationalities', views.import_nationalities, name='import_nationalities'),
    path('import_specialization', views.import_specialization, name='import_specialization'),

    path('import_employees', views.import_employees, name='import_employees'),
]

hr/models.py
from django.db import models
from convertdate import islamic

# Create your models here.

class Eclass(models.Model):
    className = models.CharField(max_length=50)

    def __str__(self):
        return self.className

    class Meta:
        verbose_name = 'Eclass'
        verbose_name_plural = 'Eclasses'

class Nationality(models.Model):
    nationality_name = models.CharField(max_length=50)

    def __str__(self):
        return self.nationality_name

    class Meta:
        verbose_name = 'Nationality'
        verbose_name_plural = 'Nationalities'


class Job(models.Model):
    jobName = models.CharField(max_length=50)

    def __str__(self):
        return self.jobName

    class Meta:
        verbose_name = 'Job'
        verbose_name_plural = 'Jobs'

class Specialization(models.Model):
    spName = models.CharField(max_length=60)

    def __str__(self):
        return self.spName

    class Meta:
        verbose_name = 'Specialization'
        verbose_name_plural = 'Specializations'

class GeneralSpecialization(models.Model):
    gsName = models.CharField(max_length=60)

    def __str__(self):
        return self.gsName

    class Meta:
        verbose_name = 'GeneralSpecialization'
        verbose_name_plural = 'GeneralSpecializations'

class Area_side(models.Model):
    area_side_name = models.CharField(max_length=75)

    def __str__(self):
        return self.area_side_name

class Actions(models.Model):
    action_name = models.CharField(max_length=50)

    def __str__(self):
        return self.action_name


class Employee(models.Model):
    JOB_TYPES = [
        (1, "خدمة مدنية"),
        (2, "تشغيل ذاتي"),
    ]

    EMPTYPE = [
        (1, "Employee"),
        (2, "SOP")
    ]
    SEX = [
        (1, "ذكر"),
        (2, "انثي"),
    ]

    emptype = models.IntegerField(choices=EMPTYPE, null=True, blank=True)
    jobtype = models.IntegerField(choices=JOB_TYPES, null=True, blank=True)
    identity = models.IntegerField(null=True, blank=True)
    eclass = models.ForeignKey(Eclass, on_delete=models.CASCADE, related_name="eclass", null=True, blank=True)
    empno = models.BigIntegerField()
    ename = models.CharField(max_length=75)
    telNo = models.CharField(max_length=15, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    nationality = models.ForeignKey(Nationality, on_delete=models.CASCADE, related_name="nationality", null=True, blank=True)
    sex = models.IntegerField(choices=SEX, null=True, blank=True)
    bdate = models.DateField(null=True, blank=True)
    job_title = models.ForeignKey(Job,  on_delete=models.CASCADE, null=True, blank=True)
    rank = models.ForeignKey(Specialization, on_delete=models.CASCADE, related_name="specialization", null=True, blank=True)
    general_specialization = models.ForeignKey(GeneralSpecialization, on_delete=models.CASCADE, related_name="generalspecialization", null=True, blank=True)
    job_id = models.CharField(max_length=20, null=True, blank=True)
    job_owner = models.CharField(max_length=75, null=True, blank=True)
    owner_side = models.CharField(max_length=75, null=True, blank=True)
    actual_work_area = models.CharField(max_length=75, null=True, blank=True)
    actual_work_side = models.CharField(max_length=100, null=True, blank=True)
    area_side_type = models.ForeignKey(Area_side, on_delete=models.CASCADE, null=True, blank=True)
    adminstrator = models.CharField(max_length=90, null=True, blank=True)
    lastAction_date = models.CharField(max_length=20, null=True, blank=True)
    last_action = models.ForeignKey(Actions, on_delete=models.CASCADE, null=True, blank=True)
    manager_name = models.CharField(max_length=75, null=True, blank=True)
    hire_date = models.CharField(max_length=20, null=True, blank=True)
    ministry_attachment = models.CharField(max_length=20, null=True, blank=True)
    country_attachement_date = models.CharField(max_length=20, null=True, blank=True)
    owner_status = models.CharField(max_length=75, null=True, blank=True)
    service_type = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.ename

    class Meta:
        verbose_name = 'Employee'
        verbose_name_plural = 'Employees'

    # @property
    # def hiredate(self):
    #     gregorian_date = self.hire_date
    #     hijri_date = islamic.from_gregorian(gregorian_date.year, gregorian_date.month, gregorian_date.day)
    #     return f"{hijri_date[2]}-{hijri_date[1]}-{hijri_date[0]}"
    #
    # @property
    # def country_attachment(self):
    #     gregorian_date = self.country_attachement_date
    #     hijri_date = islamic.from_gregorian(gregorian_date.year, gregorian_date.month, gregorian_date.day)
    #     return f"{hijri_date[2]}-{hijri_date[1]}-{hijri_date[0]}"







from django.db import models

# Create your models here.

hr/forms.py
from django import forms
# from .models import empno, ename, identifyno, jobtype, emptype, eclass, telNo, email, nationality, sex,bdate, job_title, rank, general_specialization, job_id, job_owner, owner_side, actual_work_area, actual_work_side, area_side_name, last_wag, attachment_date, hire_date, country_attachement_date, owner_status, end_service_date
from .models import Employee

class EmployeeForm(forms.ModelForm):


    class Meta:
        model = Employee
        # fields = ('empno', 'ename', 'identifyno', 'jobtype', 'emptype', 'eclass', 'telNo', 'email', 'nationality', 'sex','bdate', 'job_title', 'rank', 'general_specialization', 'job_id', 'job_owner', 'owner_side', 'actual_work_area', 'actual_work_side', 'area_side_name', 'last_wag', 'attachment_date', 'hire_date', 'country_attachement_date', 'owner_status', 'end_service_date')
        fields = ['emptype', 'jobtype', 'identity', 'eclass', 'empno', 'ename', 'telNo', 'email', 'nationality', 'sex', 'bdate', 'job_title', 'rank', 'general_specialization', 'job_id', 'job_owner', 'owner_side', 'actual_work_area', 'actual_work_side', 'area_side_type', 'adminstrator', 'lastAction_date', 'last_action', 'manager_name', 'hire_date', 'ministry_attachment', 'country_attachement_date', 'owner_status', 'service_type']
        # fields = '__all__'

        widgets = {
            'emptype': forms.Select(attrs={'class': ' form-select inputs'}),
            'jobtype': forms.Select(attrs={'class': 'inputs form-select'}),
            'identity': forms.TextInput(attrs={'class': 'inputs form-control', 'placeholder': "Identity Number"}),
            'eclass': forms.Select(attrs={'class': 'inputs form-select'}),
            'empno': forms.TextInput(attrs={'class': 'inputs form-control', 'placeholder': "Employee Number"}),
            'ename': forms.TextInput(attrs={'class': 'inputs form-control', 'placeholder': "Employee Name"}),
            'telNo': forms.TextInput(attrs={'class': 'form-control inputs', 'placeholder': "Telephone Number"}),
            'email': forms.EmailInput(attrs={'class': 'form-control inputs', 'placeholder': "Email"}),
            'nationality': forms.Select(attrs={'class': 'form-control inputs'}),
            'sex': forms.Select(attrs={'class': 'form-select inputs'}),
            'bdate': forms.DateInput(attrs={'type': 'date', 'class': 'form-control inputs', 'placeholder': "Birth Date"}),
            'job_title': forms.Select(attrs={'class': 'form-select inputs'}),
            'rank': forms.Select(attrs={'class': 'form-select inputs'}),
            'general_specialization': forms.Select(attrs={'class': 'form-select inputs'}),
            'job_id': forms.TextInput(attrs={'class': 'form-control inputs', 'placeholder': "Job ID"}),
            'job_owner': forms.TextInput(attrs={'class': 'form-control inputs', 'placeholder': "Job Owner"}),
            'owner_side': forms.TextInput(attrs={'class': 'form-control inputs', 'placeholder': "Owner Side"}),
            'actual_work_area': forms.TextInput(attrs={'class': 'form-control inputs', 'placeholder': "Actual Work Area"}),
            'actual_work_side': forms.TextInput(attrs={'class': 'form-control inputs', 'placeholder': "Actual Work Side"}),
            'area_side_type': forms.Select(attrs={'class': 'form-select inputs'}),
            'adminstrator': forms.TextInput(attrs={'class': 'form-control inputs', 'placeholder': "Administrator"}),
            'lastAction_date': forms.DateInput(attrs={'type': 'date', 'class': 'form-control inputs', 'placeholder': "Last Action Date"}),
            'last_action': forms.Select(attrs={'class': 'form-select inputs'}),
            'manager_name': forms.TextInput(attrs={'class': 'form-control inputs', 'placeholder': "Manager Name"}),
            'hire_date': forms.DateInput(attrs={'type': 'date', 'class': 'form-control inputs', 'placeholder': 'Hire Date'}),
            'ministry_attachment': forms.TextInput(attrs={'class': 'form-control inputs', 'placeholder':"ministry attachments"}),
            'country_attachement_date': forms.DateInput(attrs={'type': 'date', 'class': 'form-control inputs', 'placeholder': "Country Attachment Date"}),
            'owner_status': forms.TextInput(attrs={'class': 'form-control inputs', 'placeholder': "Owner Status"}),
            'service_type': forms.NumberInput(attrs={'class': 'form-control inputs', 'placeholder': "Service Type"}),
        }

hr/views.py
from django.shortcuts import render, redirect
from venv import logger
from django.views.generic.list import ListView
from django.forms import ValidationError
from django.http import Http404, JsonResponse
from django.shortcuts import render, redirect
from django.core.management import call_command
from django.contrib import messages
from .models import Employee
from .forms import EmployeeForm
import os
# Create your views here.


class Hr_main_view(ListView):
    model = Employee
    template_name = 'hr/hr_main.html'
    context_object_name = 'employees'
    paginate_by = 10

   


# def empl(request):
#     employees = Employee.objects.filter()[:5]
#     return render(request, 'hr/employees.html', {'employees': employees})



# def hr(request):
#     return render(request, 'hr/employees.html')

def newemployee(request):
    eform = EmployeeForm()
    return render(request, 'hr/new_employee.html', {'eform': eform})

def emp(request):
    # emp = Employee.objects.all()
    eform = EmployeeForm()
    return render(request, 'emp.html', {'eform':eform})

def save_emp(request):
    if request.method == "POST":
        eform = EmployeeForm(request.POST)
        # print(request.POST)
        try:
            if eform.is_valid():
                eform.save()
                return redirect('/')
            else:
                print(eform.errors)
        except ValidationError as ve:
            # Handle specific ValueError
            logger.error(f"ValueError occurred: {str(ve)}")
            return JsonResponse({'error': f"ValueError: {str(ve)}"}, status=400)

        except KeyError as ke:
            # Handle missing keys in POST data
            logger.error(f"KeyError occurred: {str(ke)}")
            return JsonResponse({'error': f"KeyError: {str(ke)}"}, status=400)

        except Exception as e:
            # Catch any other exceptions
            logger.error(f"An unexpected error occurred: {str(e)}")
            return JsonResponse({'error': f"An error occurred: {str(e)}"}, status=500)
    return redirect('/')
    # return render(request, 'emp.html', {'eform':eform})


def import_actions(request):
    if request.method == 'POST':
        try:
            call_command('actions')
            messages.success(request, "successfully imported")
        except Exception as e:
            messages.error(request, f'ERROR importing {e}')
        return redirect('/')
    else:
        redirect('/')
    return render(request, 'homepage.html')


def import_area_side(request):
    if request.method == 'POST':
        try:
            call_command('areasides')
            messages.success(request, "successfully imported")
        except Exception as e:
            messages.error(request, f'ERROR importing {e}')
        return redirect('/')
    else:
        redirect('/')
    return render(request, 'homepage.html')

def import_eclass(request):
    if request.method == 'POST':
        try:
            call_command('eclass')
            messages.success(request, "successfully imported")
        except Exception as e:
            messages.error(request, f'ERROR importing {e}')
        return redirect('/')
    else:
        redirect('/')
    return render(request, 'homepage.html')


def import_general_specialization(request):
    if request.method == 'POST':
        try:
            call_command('general_sp')
            messages.success(request, "successfully imported")
        except Exception as e:
            messages.error(request, f'ERROR importing {e}')
        return redirect('/')
    else:
        redirect('/')
    return render(request, 'homepage.html')

def import_jobs(request):
    if request.method == 'POST':
        try:
            call_command('job')
            messages.success(request, "successfully imported")
        except Exception as e:
            messages.error(request, f'ERROR importing {e}')
        return redirect('/')
    else:
        redirect('/')
    return render(request, 'homepage.html')

def import_nationalities(request):
    if request.method == 'POST':
        try:
            call_command('nationality')
            messages.success(request, "successfully imported")
        except Exception as e:
            messages.error(request, f'ERROR importing {e}')
        return redirect('/')
    else:
        redirect('/')
    return render(request, 'homepage.html')

def import_specialization(request):
    if request.method == 'POST':
        try:
            call_command('rank')
            messages.success(request, "successfully imported")
        except Exception as e:
            messages.error(request, f'ERROR importing {e}')
        return redirect('/')
    else:
        redirect('/')
    return render(request, 'homepage.html')


def import_employees(request):
    if request.method == 'POST':
        try:
            call_command('emp')
            messages.success(request, "successfully imported")
        except Exception as e:
            messages.error(request, f'ERROR importing {e}')
        return redirect('/')
    else:
        redirect('/')
    return render(request, 'homepage.html')

templates/hr/command_store.html
<div class="content">
    <h2>Commands</h2>
    <div class="list-item-group">
        <div class="list-item">
            <form action="{% url 'hr:import_actions' %}" method="POST">
                {% csrf_token %}
                <button type='submit'  class='btn-null'>import actions</button>
            </form>
        </div>
        <div class="list-item">
            <form action="{% url 'hr:import_area_side' %}" method="POST">
                {% csrf_token %}
                <button type='submit'  class='btn-null'>import area side</button>
            </form>
        </div>
        <div class="list-item">
            <form action="{% url 'hr:import_eclass' %}" method="POST">
                {% csrf_token %}
                <button type='submit'  class='btn-null'>import Eclass</button>
            </form>
        </div>
        <div class="list-item">
            <form action="{% url 'hr:import_general_specialization' %}" method="POST">
                {% csrf_token %}
                <button type='submit'  class='btn-null'>import general specialization</button>
            </form>
        </div>
        <div class="list-item">
            <form action="{% url 'hr:import_jobs' %}" method="POST">
                {% csrf_token %}
                <button type='submit'  class='btn-null'>import jobs</button>
            </form>
        </div>
        <div class="list-item">
            <form action="{% url 'hr:import_nationalities' %}" method="POST">
                {% csrf_token %}
                <button type='submit'  class='btn-null'>import nationalities</button>
            </form>
        </div>
        <div class="list-item">
            <form action="{% url 'hr:import_specialization' %}" method="POST">
                {% csrf_token %}
                <button type='submit'  class='btn-null'>import specialization</button>
            </form>
        </div>
        <br>
        <div class="list-item">
            <form action="{% url 'hr:import_employees' %}" method="POST">
                {% csrf_token %}
                <button type='submit'  class='btn-null'>import employees</button>
            </form>
        </div>
    </div>
    </p>
</div>

templates/hr/hr_main.html
{% extends 'base.html' %}
{% load static %}
{% block container %}
<link rel="stylesheet" href="{% static 'css/hr/employees.css' %}">
<div class="bg">
    <h1 style="text-align: center">الموارد البشرية</h1>
    <h3 style="text-align: center">شؤون الموظفين</h3>
    <div class="btn-groups border" role="group" aria-label="Basic example">
        <a href="{% url 'hr:newemployee' %}" type="button" class="btn border-none">اضافة موظف</a>
<!--        <a href="" type="button" class="btn btn-warning border-none">اضافة موظفين </a>-->
    </div>
    <hr>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th scope="م" class="bg-secondary text-white">#</th>
            <th scope="col" class="bg-secondary text-white">الاسم</th>
            <th scope="col" class="bg-secondary text-white">الجنسية</th>
            <th scope="col" class="bg-secondary text-white">المرتبة</th>
            <th scope="col" class="bg-secondary text-white">اخر واقعة</th>
        </tr>
        </thead>
        <tbody>
        {% for employee in employees %}
        <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td>{{employee.ename}}</td>
            <td>{{employee.nationality }}</td>
            <td>{{employee.rank }}</td>
            <td>{{employee.last_action }}</td>
        </tr>
        {% endfor %}

        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
    
                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
    
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>

            </tbody>
            </table>
</div>

{% endblock %}

templates/hr/new_employee.html
{% extends 'base.html' %}
{% load static %}
{% block container %}
<link rel="stylesheet" href="{% static 'css/hr/employees.css' %}">
<link rel="stylesheet" href="{% static 'css/forms.css' %}">
<!--<link rel="stylesheet" href="{% static 'css/main.css' %}">-->

<section class="bg">
    <h2 class="text-primary pb-3">        موظف جديد    </h2>
    <div>
        <form action="save_emp" method="POST">
            {% csrf_token %}
            <div class="row g-3">
                <div class="col-md-6">
                    <label for="" class="form-label">نوع الموظف</label>
                    {{eform.emptype}}
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">نوع الوظيفة</label>
                    {{eform.jobtype}}
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">رقم الهوية</label>
                    {{eform.identity}}
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">فئة الموظف</label>
                    {{eform.eclass}}
                </div>
                <div class="col-md-3">
                    <label for="" class="form-label">رقم الموظف</label>
                    {{eform.empno}}
                </div>
                <div class="col-md-9">
                    <label for="" class="form-label">اسم الموظف</label>
                    {{eform.ename}}
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">رقم الجوال</label>
                    {{eform.telNo}}
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">البريد الالكتروني</label>
                    {{eform.email}}
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">الجنسية</label>
                    {{eform.nationality}}
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">الجنس</label>
                    {{eform.sex}}
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">تاريخ الميلاد</label>
                    {{eform.bdate}}
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">مسمي الوظيفة</label>
                    {{eform.job_title}}
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">اسم المرتبة</label>
                    {{eform.rank}}
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">التخصص العام</label>
                    {{eform.general_specialization}}
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">رقم الوظيفة</label>
                    {{eform.job_id}}
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">ملاك المنطقة للوظيفة</label>
                    {{eform.job_owner}}
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">جهة الملاك للوظيفة</label>
                    {{eform.owner_side}}
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">منطقة العمل الفعلية</label>
                    {{eform.actual_work_area}}
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">جهة العمل الفعلية</label>
                    {{eform.actual_work_side}}
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">اسم نوع الجهة</label>
                    {{eform.area_side_type}}
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">اسم المسير</label>
                    {{eform.adminstrator}}
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">تاريخ اخر واقعة</label>
                    {{eform.lastAction_date}}
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">اسم اخر واقعة</label>
                    {{eform.last_action}}
                </div>
                <div>
                    <label for="" class="form-label">اسم المدير</label>
                    {{eform.manager_name}}
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">تاريخ الالتحاق بالوزارة</label>
                    {{eform.ministry_attachment}}
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">تاريخ التعيين</label>
                    {{eform.hire_date}}
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">تاريخ الالتحاق بالدولة</label>
                    {{eform.country_attachement_date}}
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">حالة مطابقة الملاك لجهة العمل</label>
                    {{eform.owner_status}}
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">نوع نهاية الخدمة</label>
                    {{eform.service_type}}
                </div>
            </div>
            <button type="submit" class=" mt-3 btn btn-primary w-75 m-auto">save</button>
        </form>
    </div>
</section>


{% endblock  %}